import numpy as np
import pandas as pd


def generate_mock_ct_series_acquisition_parameters():
    """
    This function generates synthetic ct series acquisition parameters.

    Returns
    -------
    ct_series_acquisition_parameters : dict
        Dictionary containing synthetic acquisition parameters. Parameters having been set to None are expected (in a
        clinical case) to be populated by relevant values.
    """

    ct_series_acquisition_parameters = {"ImageDimensions" : [10, 10],
                                        "ImagePlanarPositionPatient": None,
                                        "PixelSpacing" : [1.00, 1.00],
                                        "SliceThickness" : 3.00,
                                        "SpacingBetweenSlices": None,
                                        "ImageOrientationPatient" : None,
                                        "PatientPosition": None,
                                        "FrameOfReferenceUID" : None}

    return ct_series_acquisition_parameters


def generate_mock_structures_masks():
    """
    This function generates synthetic structures (volumetric) masks representing two organs at risk (OARs) and one
    tumorous structure. All structures are defined as simple cuboids embedded within a volume of shape (10, 10, 10).
    Each structure spans the full extent of the first axis and occupies distinct, non-overlapping regions in the
    remaining dimensions.

    Returns
    -------
    structures_masks : list of dict
        List of generated synthetic structures (volumetric) masks. Parameters having been set to None are expected (in a
        clinical case) to be populated by relevant values.
    """

    oar_1_volumetric_mask = np.zeros((10, 10, 10), dtype=np.uint8)
    oar_1_volumetric_mask[:,2,1:5] = 1

    oar_2_volumetric_mask = np.zeros((10, 10, 10), dtype=np.uint8)
    oar_2_volumetric_mask[:,1:4,6:9] = 1

    tumorous_structure_volumetric_mask = np.zeros((10, 10, 10), dtype=np.uint8)
    tumorous_structure_volumetric_mask[:,5:9,1:9] = 1

    structures_masks = [{"StructureName" : "OAR_1",
                         "StructureType" : "Organ At Risk",
                         "PlanarMasksOnReferencedImages" : None,
                         "VolumetricMask" : oar_1_volumetric_mask},
                        {"StructureName" : "OAR_2",
                         "StructureType": "Organ At Risk",
                         "PlanarMasksOnReferencedImages" : None,
                         "VolumetricMask" : oar_2_volumetric_mask},
                        {"StructureName" : "TumorousStructure",
                         "StructureType": "Tumorous Structure",
                         "PlanarMasksOnReferencedImages" : None,
                         "VolumetricMask" : tumorous_structure_volumetric_mask}]

    return structures_masks


def generate_mock_dose_map():
    """
    This function generates a synthetic (volumetric) dose map. The dose distribution represents a non-uniformly irradiated
    cubic volume of shape (10, 10, 10). Dose values are non-zero only within an inner cuboid of shape (10, 6, 6). Each
    plane (defined by the first index of the dose map array) corresponds to a different percentage of the prescribed
    dose (ranging from 30% to 120%).

    Returns
    -------
    dose_map : dict
        Dictionary containing the generated synthetic (volumetric) dose map. An additional key-value pair is added
        (compared to the output of "generate_dose_maps" function), which corresponds to the prescribed dose to the
        synthetic tumorous structure (generated by "generate_mock_structures_masks" function). Parameters having been
        set to None are expected (in a clinical case) to be populated by relevant values.
    """

    prescribed_dose = 100 # Gy
    volumetric_dose_map = np.zeros((10, 10, 10), dtype=np.uint16)

    for dose_plane_index in range(volumetric_dose_map.shape[0]):
        volumetric_dose_map[dose_plane_index, 2:8, 2:8] = (0.3 + (0.1 * dose_plane_index)) * prescribed_dose

    dose_map = {"PlanarDoseMaps" : None, "VolumetricDoseMap" : volumetric_dose_map, "PrescribedDose" : prescribed_dose}

    return dose_map


def generate_mock_dvh():
    """
    This function generates a synthetic DVH corresponding to a single (irradiated) structure. The structure consists of
    20 voxels, with a voxel volume equal to 0.003 cc. The absorbed dose lies within [0, 1] Gy and the structure's voxels
    have been placed to 10 uniform dose bins of width 0.1 Gy.

    Returns
    -------
    dvh : dict
        Dictionary containing the generated synthetic DVH. Parameters having been set to None are expected (in a
        clinical case) to be populated by relevant values.
    """

    structure_name = "Mock structure"

    differential_dvh = np.array([2, 4, 2, 3, 1, 1, 2, 1, 3, 1])
    dose_bin_edges = np.linspace(0, 1, 11)
    dose_bin_width = 0.10
    voxel_volume = 0.003
    structure_voxels = np.sum(differential_dvh)
    structure_volume =  structure_voxels * voxel_volume

    normalized_cumulative_dvh = 100 * (1 - (np.cumsum(differential_dvh) / structure_voxels))

    # Slightly modify the cumulative dose volume histogram so that its first element corresponds to the leftmost dose
    # bin edge (0). In other words, the first element is equal to the percentage of the structure's volume that receives
    # zero (or more) Gy (100%).
    normalized_cumulative_dvh = np.concat([np.array([100]), normalized_cumulative_dvh])

    absolute_volume_cumulative_dvh = (normalized_cumulative_dvh/100) * structure_volume

    dvh = {"StructureName" : structure_name,
           "StructureType" : "Organ At Risk",
           "VolumetricMask" : None,
           "DifferentialDoseVolumeHistogram" : differential_dvh,
           "NormalizedCumulativeDoseVolumeHistogram" : normalized_cumulative_dvh,
           "AbsoluteVolumeCumulativeDoseVolumeHistogram": absolute_volume_cumulative_dvh,
           "StructureVolumeInCubicCentimeters": structure_volume,
           "StructureVoxels": structure_voxels,
           "VoxelVolumeInCubicCentimeters": voxel_volume,
           "DoseBinEdges": dose_bin_edges,
           "DoseBinWidth": dose_bin_width}

    return dvh


def generate_mock_dose_constraints():
    """
    This function generates a pandas.DataFrame containing synthetic dose constraints associated with a single, synthetic
    structure. The constraints are constructed to represent multiple clinical scenarios, ranging from fully satisfied to
    fully violated constraints. Each row of the dataframe corresponds to a different clinical scenario (fulfilled
    constraints, partially fulfilled constraints, borderline violated constraints and violated constraints), while
    columns represent different types of constraints. The values appearing as comments on the right side of each
    constraint definition, correspond to the synthetic DVH (generated by "generate_mock_dvh" function).

    Returns
    -------
    constraints : pandas.DataFrame
        Dataframe containing synthetic constraints.
    """

    cases = ["Fulfilled constraints", "Partially fulfilled constraints", "Borderline violated constraints", "Violated constraints"]

    constraints = pd.DataFrame("", index=range(len(cases)),
                                        columns=['Organ', 'Endpoint', 'Dmax (Gy)', 'Dmean (Gy)', 'Vd (%, Gy)',
                                                 'Dv (Gy, %)', 'Dabsv (Gy, cc)', 'Notes'])

    constraints.loc[0, "Organ"] = "Mock structure"
    constraints.loc[0, "Endpoint"] = "Fulfilled constraints"
    constraints.loc[0, "Dmax (Gy)"] = 1.00  # 0.95
    constraints.loc[0, "Dmean (Gy)"] = 0.70  # 0.44
    constraints.loc[0, "Vd (%, Gy)"] = [(80, 0.3), (60, 0.4)]  # (60, 0.3), (45, 0.4)
    constraints.loc[0, "Dv (Gy, %)"] = [(0.45, 70), (0.40, 60)]  # (0.20, 70), (0.30, 60)
    constraints.loc[0, "Dabsv (Gy, cc)"] = [(0.55, 0.036), (0.40, 0.042)]  # (0.30, 0.036), (0.20, 0.042)
    constraints.loc[0, "Notes"] = "-"

    constraints.loc[1, "Organ"] = "Mock structure"
    constraints.loc[1, "Endpoint"] = "Partially fulfilled constraints"
    constraints.loc[1, "Dmax (Gy)"] = 1.00  # 0.95
    constraints.loc[1, "Dmean (Gy)"] = 0.70  # 0.44
    constraints.loc[1, "Vd (%, Gy)"] = [(80, 0.3), (40, 0.4)]  # (60, 0.3), (45, 0.4)
    constraints.loc[1, "Dv (Gy, %)"] = [(0.45, 70), (0.20, 60)]  # (0.20, 70), (0.30, 60)
    constraints.loc[1, "Dabsv (Gy, cc)"] = [(0.55, 0.036), (0.10, 0.042)]  # (0.30, 0.036), (0.20, 0.042)
    constraints.loc[1, "Notes"] = "-"

    constraints.loc[2, "Organ"] = "Mock structure"
    constraints.loc[2, "Endpoint"] = "Borderline violated constraints"
    constraints.loc[2, "Dmax (Gy)"] = 0.95  # 0.95
    constraints.loc[2, "Dmean (Gy)"] = 0.44  # 0.44
    constraints.loc[2, "Vd (%, Gy)"] = (60, 0.3)  # (60, 0.3)
    constraints.loc[2, "Dv (Gy, %)"] = (0.20, 70)  # (0.20, 70)
    constraints.loc[2, "Dabsv (Gy, cc)"] = (0.30, 0.036)  # (0.30, 0.036)
    constraints.loc[2, "Notes"] = "-"

    constraints.loc[3, "Organ"] = "Mock structure"
    constraints.loc[3, "Endpoint"] = "Violated constraints"
    constraints.loc[3, "Dmax (Gy)"] = 0.55  # 0.95
    constraints.loc[3, "Dmean (Gy)"] = 0.20  # 0.44
    constraints.loc[3, "Vd (%, Gy)"] = (40, 0.3)  # (60, 0.3)
    constraints.loc[3, "Dv (Gy, %)"] = (0.05, 70)  # (0.20, 70)
    constraints.loc[3, "Dabsv (Gy, cc)"] = (0.15, 0.036)  # (0.30, 0.036)
    constraints.loc[3, "Notes"] = "-"

    return constraints


def generate_mock_evaluation_table():
    """
    This function generates a pandas.DataFrame intended to store the results of constraints evaluation. Each row
    corresponds to a different clinical scenario, while columns represent different types of constraints.

    Returns
    -------
    evaluation_table : pandas.DataFrame
        Empty dataframe.
    """

    cases = ["Fulfilled constraints", "Partially fulfilled constraints", "Borderline violated constraints", "Violated constraints"]

    columns = ["Organ At Risk (OAR)", "Dmax (Gy)", "Dmean (Gy)",
               "Vd (%, Gy)", "Dv (Gy, %)", "Dabsv (Gy, cc)"]

    evaluation_table = pd.DataFrame("", index=range(len(cases)), columns=columns)

    return evaluation_table