"""
This module provides pytest-based unit tests for validating the implementation of the function related to the
generation of the DVHs ("generate_dose_volume_histograms" function). Synthetic data is used to ensure deterministic and
reproducible test outcomes. All the values that are used during the assessments have been calculated independently
(manually), using the synthetic data provided by "mock_data" module functions. All synthetic structures (generated by
"generate_mock_structures_masks" function) are taken into account.
"""

import numpy as np
import pytest
from computations.dose_volume_histograms import generate_dose_volume_histogram
from tests.mock_data import generate_mock_ct_series_acquisition_parameters, generate_mock_structures_masks, generate_mock_dose_map


@pytest.fixture(scope="module")
def series_acquisition_parameters():
    return generate_mock_ct_series_acquisition_parameters()


@pytest.fixture(scope="module")
def structures_masks():
    return generate_mock_structures_masks()


@pytest.fixture(scope="module")
def dose_maps():
    return generate_mock_dose_map()


def test_generate_dose_volume_histograms(series_acquisition_parameters, structures_masks, dose_maps, dose_bin_width = 10):

    dvhs = generate_dose_volume_histogram(series_acquisition_parameters, structures_masks, dose_maps, dose_bin_width)
    oar_1_dvh = dvhs[0]
    oar_2_dvh = dvhs[1]
    tumorous_structure_dvh = dvhs[2]

    assert np.array_equal(oar_1_dvh["DifferentialDoseVolumeHistogram"],
                          np.array([10, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])) == True
    assert np.allclose(oar_1_dvh["NormalizedCumulativeDoseVolumeHistogram"],
                       np.array([100, 75, 75, 75, 67.5, 60, 52.5, 45, 37.5, 30, 22.5, 15, 7.5, 0]), rtol = 0, atol = 0.01) == True
    assert np.allclose(oar_1_dvh["AbsoluteVolumeCumulativeDoseVolumeHistogram"],
                       np.array([0.12, 0.09, 0.09, 0.09, 0.081, 0.072, 0.063, 0.054, 0.045, 0.036, 0.027, 0.018, 0.009, 0]), rtol = 0, atol = 0.0001) == True
    assert np.allclose(oar_1_dvh["StructureVolumeInCubicCentimeters"], 0.12, rtol = 0, atol = 0.001) == True
    assert oar_1_dvh["StructureVoxels"] == 40
    assert np.allclose(oar_1_dvh["VoxelVolumeInCubicCentimeters"], 0.003, rtol = 0, atol = 0.0001) == True
    assert np.array_equal(oar_1_dvh["DoseBinEdges"], np.arange(0, 130 + 10, 10)) == True

    assert np.array_equal(oar_2_dvh["DifferentialDoseVolumeHistogram"],
                          np.array([50, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])) == True
    assert np.allclose(oar_2_dvh["NormalizedCumulativeDoseVolumeHistogram"],
                       np.array([100, 44.4, 44.4, 44.4, 40, 35.5, 31.1, 26.6, 22.2, 17.7, 13.3, 8.8, 4.4, 0]), rtol = 0, atol = 0.1) == True
    assert np.allclose(oar_2_dvh["AbsoluteVolumeCumulativeDoseVolumeHistogram"],
                       np.array([0.27, 0.12, 0.12, 0.12, 0.108, 0.096, 0.084, 0.072, 0.06, 0.048, 0.036, 0.024, 0.012, 0]), rtol = 0, atol = 0.0001) == True
    assert np.allclose(oar_2_dvh["StructureVolumeInCubicCentimeters"], 0.27, rtol = 0, atol = 0.001) == True
    assert oar_2_dvh["StructureVoxels"] == 90
    assert np.allclose(oar_2_dvh["VoxelVolumeInCubicCentimeters"], 0.003, rtol=0, atol=0.0001) == True
    assert np.array_equal(oar_2_dvh["DoseBinEdges"], np.arange(0, 130 + 10, 10)) == True

    assert np.array_equal(tumorous_structure_dvh["DifferentialDoseVolumeHistogram"],
                          np.array([140, 0, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18])) == True
    assert np.allclose(tumorous_structure_dvh["NormalizedCumulativeDoseVolumeHistogram"],
                       np.array([100, 56.25, 56.25, 56.25, 50.625, 45, 39.375, 33.75, 28.125, 22.5, 16.875, 11.250, 5.625, 0]), rtol = 0, atol = 0.0001) == True
    assert np.allclose(tumorous_structure_dvh["AbsoluteVolumeCumulativeDoseVolumeHistogram"],
                       np.array([0.96, 0.54, 0.54, 0.54, 0.486, 0.432, 0.378, 0.324, 0.270, 0.216, 0.162, 0.108, 0.054, 0]), rtol = 0, atol = 0.0001 ) == True
    assert np.allclose(tumorous_structure_dvh["StructureVolumeInCubicCentimeters"], 0.96, rtol = 0, atol = 0.001) == True
    assert tumorous_structure_dvh["StructureVoxels"] == 320
    assert np.allclose(tumorous_structure_dvh["VoxelVolumeInCubicCentimeters"], 0.003, rtol=0, atol=0.0001) == True
    assert np.array_equal(tumorous_structure_dvh["DoseBinEdges"], np.arange(0, 130 + 10, 10)) == True